[package]
name = "read_bigdata"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
num_cpus = "1.16.0"